# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Herramientas de Ciudadano Inteligente
email: herramientas@ciudadanointeligente.org
description: "Con nuestras herramientas puedes crear mejores democracias y mejores sociedades"
baseurl: "https://herramientas.ciudadanointeligente.org/" # the subpath of your site, e.g. /blog
url: "https://herramientas.ciudadanointeligente.org/" # the base hostname & protocol for your site
twitter_username: ciudadanoi
github_username:  ciudadanointeligente
analytics: UA-76464035-1

# Build settings
markdown: kramdown
collections:
  category:
    output: true
  user:
    output: true
defaults:
  -
    scope:
      path: ""
      type: user
    values:
      layout: "user"
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"


# Prose
prose:
  ignore:
    - _category
    - /_layouts
    - /_sass
    - /css
    - /js
    - /_includes/fb_head.html
    - /_includes/footer.html
    - /_includes/head.html
    - /_includes/header.html
    - /_includes/highlighted.html
    - /_includes/icon-github.html
    - /_includes/icon-github.svg
    - /_includes/icon-twitter.html
    - /_includes/icon-twitter.svg
    - /_includes/post-date.html
    - /_includes/post-preview.html
    - .gitignore
    - CNAME
    - favicon.ico
    - LICENSE
    - README.md
    - _config.yml
    - feed.xml
